const ADD_TODO = "ADD_TODO"
const TOGGLE_TODO = "TOGGLE_TODO"
const SET_VISIBILITY_FILTER = "SET_VISIBILITY_FILTER"
const REMOVE_TODO = "REMOVE_TODO"

export { ADD_TODO, TOGGLE_TODO, SET_VISIBILITY_FILTER, REMOVE_TODO }
